### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by equippedmandingo** [mariusbancila/croncpp#20]
I am trying to set up a timer. However "cron_next" doesn't return correct values for the timer.

```
        auto expr{ "* 0/5 * * * ?" };
        auto cron = cron::make_cron(expr);

        std::time_t now = std::time(0);
        std::time_t next = cron::cron_next(cron, now);
        std::cout << "set timer for: " << next - now << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(next - now));

        cron = cron::make_cron(expr); // construct again?
        now = std::time(0); // new time or old time?
        next = cron::cron_next(cron, now);
        std::cout << "set timer for: " << next - now << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(next - now));

        cron = cron::make_cron(expr); // construct again?
        now = std::time(0); // new time or old time?
        next = cron::cron_next(cron, now);
        std::cout << "set timer for: " << next - now << std::endl;

```

**Comment by mariusbancila** [comment]
Your expression means "every second every 5 minutes". So sometimes, it will return you the next second, other times it will return a longer time.

0/5 means it will consider the minute 0, 5, 10, 15, 20, 25, 30, 25, 40, 45, 50, 55.

So:
- if the time `now` is 15:00:12, it will return 15:00:13, then 15:00:14, ... then 15:00:59 and then, the next one will be 15:05:00. 
- if the time `now` is 15:03:22, it will return 15:05:00

If you notice another behavior, then please describe it, not just the code. Pasting a code without any explanation doesn't help me understand your problem.

**Comment by equippedmandingo** [comment]
@mariusbancila Thank you for your explanation. Appreciate the help.
