### ISSUE TITLE
can not build with gcc 4.8.4

### ISSUE THREAD

**Issue by qinxin0720** [mariusbancila/croncpp#27]
https://github.com/mariusbancila/croncpp/blob/d5026f6e3813430cc334918e37bf4ac954b006ee/include/croncpp.h#L314

'auto' not allowed in lambda parameter.

**Comment by mariusbancila** [comment]
Fixed

**Comment by qinxin0720** [comment]
Thank you!

**Comment by qinxin0720** [comment]
> Fixed

Thank you!
