### ISSUE TITLE
When generated time added to an asio timer, several executions happen at the same time

### ISSUE THREAD

**Issue by SlavSlavov** [mariusbancila/croncpp#3]
In the example below I am trying to set an asio timer with the time calculated by cron_next. When the timer expires I am trying to set it again with the same cron entry (every 5 seconds). As you can see from the printed log, the timer is executed several times per second before making the next execution 5 seconds later.

Looks like cron_next can generate time which has already passed

To be executed at 1545474550000000000
Executed 1545474550000000000 at 1545474550000052948
Executed 1545474550000000000 at 1545474550000311756
Executed 1545474550000000000 at 1545474550000532974
Executed 1545474555000000000 at 1545474555000051491
Executed 1545474555000000000 at 1545474555000311948
Executed 1545474555000000000 at 1545474555000529890
Executed 1545474560000000000 at 1545474560000054536
Executed 1545474560000000000 at 1545474560000316441
Executed 1545474560000000000 at 1545474560000541654

	void doSetTimer(asio::system_timer & timer, std::chrono::system_clock::time_point timePoint)
	{
	    timer.expires_at(timePoint);

	    timer.async_wait([&timer, timePoint](std::error_code ec) {
		if (!ec) //Timed out
		{
		    std::cout << "Executed " << timePoint.time_since_epoch().count() << " at " << std::chrono::system_clock::now().time_since_epoch().count() << std::endl;
		    auto cron = cron::make_cron("*/5 * * * * ?");
		    auto timePointNew = std::chrono::system_clock::from_time_t(cron::cron_next(cron, std::time(nullptr)));
		    doSetTimer(timer, timePointNew);
		}
	    });
	}

	int main()
	{
	    auto cron = cron::make_cron("*/5 * * * * ?");
	    auto timePoint = std::chrono::system_clock::from_time_t(cron::cron_next(cron, std::time(nullptr)));

	    std::cout << "To be executed at " << timePoint.time_since_epoch().count() << std::endl;

	    asio::io_context ioContext;
	    asio::system_timer timer(ioContext);

	    doSetTimer(timer, timePoint);

	    ioContext.run_for(std::chrono::seconds(14));
	}

**Comment by SlavSlavov** [comment]
Strange, I tried with another parser - https://github.com/staticlibs/ccronexpr and it behaves exactly the same. Am I doing something wrong? If I just add 1 to the value generated by `cron_next` all seems to work fine. Like this:
`auto timePointNew = std::chrono::system_clock::from_time_t(cron::cron_next(cron, std::time(nullptr)) + 1);`

**Comment by SlavSlavov** [comment]
Looks like the problem is somewhere else and I am going to close this issue.
Looks like `std::time(nullptr)` returns a second less on my system. I'll try on other systems to see if this is true there. Getting the system time with chrono works fine. Printing the following, curt is always 1 less than cur, even if I change the order.

    time_t curt = time(NULL);
    time_t cur = std::chrono::duration_cast<std::chrono::seconds> (std::chrono::system_clock::now().time_since_epoch()).count();

**Comment by equippedmandingo** [comment]
Slav, are you still using this library? I am trying to set up a timer. However "cron_next" doesn't return correct values for the timer.
Not sure what I am doing wrong.

```
        auto expr{ "* 0/5 * * * ?" };
        auto cron = cron::make_cron(expr);

        std::time_t now = std::time(0);
        std::time_t next = cron::cron_next(cron, now);
        std::cout << "set timer for: " << next - now << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(next - now));

        cron = cron::make_cron(expr); // construct again?
        now = std::time(0); // new time or old time?
        next = cron::cron_next(cron, now);
        std::cout << "set timer for: " << next - now << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(next - now));

        cron = cron::make_cron(expr); // construct again?
        now = std::time(0); // new time or old time?
        next = cron::cron_next(cron, now);
        std::cout << "set timer for: " << next - now << std::endl;
```
